# Generated by Django 5.2.8 on 2025-12-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='unidade',
            field=models.CharField(default='UN', max_length=2),
        ),
    ]
