# Generated by Django 5.2.8 on 2025-12-05 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_produto_unidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentoitem',
            name='codigo',
        ),
    ]
