# Generated by Django 5.2.8 on 2025-11-19 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_produtos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='produtos',
            new_name='produto',
        ),
    ]
