# Generated by Django 5.2.8 on 2025-12-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_movimentoitem_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentoitem',
            name='tipomovimento',
            field=models.CharField(choices=[('+', 'ENTRADA'), ('-', 'SAIDA')], max_length=1),
        ),
    ]
