# Generated by Django 5.2.8 on 2025-12-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_movimentoitem_tipomovimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentoitem',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
