# Generated by Django 5.2.8 on 2025-12-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_movimentoitem_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='duplicata',
            name='pago',
            field=models.CharField(choices=[('P', 'PAGO'), ('E', 'EM ABERTO'), ('A', 'ATRASADO')], default='E', max_length=1),
        ),
        migrations.AddField(
            model_name='duplicata',
            name='tipo',
            field=models.CharField(choices=[('P', 'PAGAR'), ('R', 'RECEBER')], default='R', max_length=1),
        ),
        migrations.AlterField(
            model_name='movimentoitem',
            name='tipomovimento',
            field=models.CharField(choices=[('+', 'ENTRADA'), ('-', 'SAIDA'), ('$', 'CUSTO')], max_length=1),
        ),
    ]
