# Generated by Django 5.2.8 on 2025-11-19 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_produto_estoque'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='estoque',
            new_name='quantidadeestoque',
        ),
    ]
