# Generated by Django 5.2.8 on 2025-11-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_estoque_produto_quantidadeestoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='quantidadeestoque',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
