# Generated by Django 5.2.8 on 2025-12-07 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_duplicata_pago_duplicata_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duplicata',
            name='codigo',
        ),
    ]
