# Generated by Django 5.2.8 on 2025-12-16 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_duplicata_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('razaosocial', models.CharField(max_length=100)),
                ('segmento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='core.produto')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fornecedores', to='core.fornecedor')),
            ],
        ),
    ]
