# Generated by Django 5.2.8 on 2025-11-21 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_venda_itemvenda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemvenda',
            old_name='quantida',
            new_name='quantidade',
        ),
    ]
