# Generated by Django 5.2.8 on 2025-12-16 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_fornecedor_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='status',
            field=models.CharField(choices=[('F', 'Faturado'), ('A', 'Aberto')], default=2, max_length=1),
            preserve_default=False,
        ),
    ]
