# Generated by Django 5.2.8 on 2025-11-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_quantida_itemvenda_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvenda',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
