# Generated by Django 5.2.8 on 2025-11-22 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_itemvenda_preco_unitario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemvenda',
            name='codigo',
        ),
    ]
