# Generated by Django 5.2.8 on 2025-11-25 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_itemvenda_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='movimentoitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('tipomovimento', models.CharField()),
                ('qtdmovimento', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produto')),
            ],
        ),
    ]
